### PR TITLE
Noviny/make typescript work

### PR DESCRIPTION
**Pull request by Noviny**

### CODE REVIEW

**Comment by Noviny** [comment]
Okay, let's talk through the changes:

- The `allowJSX` flag has been killed, replaced by taking in an `extensions` array.
- `react-codesandboxer` now accepts both `extensions` and `template` props to change your sandboxy experience.
- Both `codesandboxer` proper and `codesandboxer-fs` adds the file type of your extension to the allowed files - `.ts` and `.tsx` files add both extension types
- `react-codesandboxer` and `codesandboxer-fs` will use the `create-react-app-typescript` template by default, unless another template is manually specified

**Comment by Noviny** [comment]
Thing to do:

What are `.tsconfig` files, and what do I need to do to handle them?

**Comment by Noviny** [comment]
@gwyneplaine

**Comment by lukebatchelor** [comment]
You likely won't need to provide one, as it'll be provided by coresandbox. Same as the webpack config

**Pull request merged**
